org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

minecraft_version=26.1.2
minecraft_version_range=[26.1, 26.2)
neo_version=26.1.2.36-beta
mod_id=mutil
mod_name=mutil
mod_license=MIT
mod_version=8.0.0
mod_group_id=se.mickelus.mutil
mod_authors=Mickelus
mod_description=A collection of utilities used by mods like tetra.
